### PR TITLE
Add symlink from themes folder to SteamUI to use the Steam Loopback as a localhost

### PR DESCRIPTION
**Pull request by joamjoamjoam**
Host Images locally using the Steam Loopback. 

Images can be referenced from CSS using url('/themes_custom/themeName/path/to/image.jpg')

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
- You seem to be checking twice if the path already exists
- Please run the create symlink function in the _main() of the plugin
- Please try except the create_symlink function, and make the function return a Result. When an exception occurs, it will log the exception

**Comment by beebls** [comment]
Aside from what suchmeme said, looks good and should hopefully allow you to achieve what you want with images

**Comment by joamjoamjoam** [comment]
Fixed. I moved the definition of create_symlink under the Class declaration for Result to allow the return annotation. I can remove the annotation or move it somewhere else if you want.

**Review by suchmememanyskill — APPROVED** [review]
I am unable to test this right now, but at a glance these changes look fine

**Review by EMERALD0874 — APPROVED** [review]
LGTM but gonna wait until SMMS has a chance to test everything

**Pull request merged**
